### PR TITLE
Draft: Tomato's sample and payload schema.

### PR DESCRIPTION
**Pull request by PeterKraus**
This PR will implement the payload and sample schema for tomato:

- [x] `BatterySample` implemented with nominal (recipe) and actual (material) capacities
- [ ] `ElectroChemPayloads` implemented, including `OpenCircuitVoltage`, `ConstantCurrent`, `ConstantVoltage`, `Loop`, `SweepCurrent`, and `SweepVoltage`
- [x] `DummyPayloads` implemented, including `Random` and `Sequential`
- [ ] Documentation
- [ ] Tests

@lorisercole, comments here are welcome.

### CODE REVIEW

**Comment by lorisercole** [comment]
HI @PeterKraus, thanks for opening this PR.
I invite you to have a look at the draft data schemas I started to write for the app:
https://github.com/epfl-theos/aurora-app/blob/main/aurora/schemas/data_schemas.py
The structure is a bit more complex (I define both `BatterySample` and `BatterySpecs`), as I am trying to reflect the data concepts that will be implemented within AiiDA.

A couple of questions about your current implementation, and some comments:
- what can a `Sample` be? Is it like a generic sample, and we can think a `BatterySample` as a subclass of it?
- in my implementation, a `BatterySample` also contains the manufacturer, composition, metadata, etc (as you suggested in the design document). We can always mark some of these parameters as optional, e.g. if I want to query for a battery of capacity X, without specifying a manufacturer/form factor/...

I also started writing a schema for electrochemical testing techniques. Again, it is a bit more complex and it should allow for some level of automatic validation.

**Comment by PeterKraus** [comment]
Excellent, thanks. Could you add me to that repository? I think it's private at the moment. In any case, it might be easiest to get it working from one branch and then PR-merge the schema here once we're happy with it.

**Comment by lorisercole** [comment]
oh right, I'll add you to my repo.
Ok yes, once the schemas work we can move them here.

**Comment by lorisercole** [comment]
Hey @PeterKraus,
Taking inspiration this PR, I have implemented a few [cycling-technique schemas](https://github.com/epfl-theos/aurora-app/blob/main/aurora/schemas/cycling.py), that I use in the app.
I also implemented an [interface](https://github.com/epfl-theos/aurora-app/blob/main/screenshots/Aurora_5.png) to customize the protocol, providing the capability to add different steps. As a result, the interface returns a list of these schema objects.

**Comment by PeterKraus** [comment]
Looks good, I noticed it when I was looking at your repo yesterday. I'll try to make a PR tomorrow/Friday with the `ConstantVoltage` and `ConstantCurrent` in it.

**Comment by PeterKraus** [comment]
Closed in favour of #8.

**Pull request closed without merging**
